spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres9
  username: postgres
  password: axror123
spring.jpa:
  hibernate.ddl-auto: update
  defer-datasource-initialization: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver