spring.datasource:
  url: jdbc:postgresql://localhost:5432/mydb
  username: myuser
  password: mypassword
spring.jpa:
  hibernate.ddl-auto: update
  defer-datasource-initialization: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect